### ISSUE TITLE
**Unclicable links**

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-app-template#108]
**Unclicable links**
1. Install an app with manifest
2. Go into that app
3. In resources try to click on some link
Result: Links are unclickable 

![Image](https://user-images.githubusercontent.com/25908728/197516915-658edbd9-e56a-45d7-8c3b-8e523386e794.png)

_Originally posted by @michalina-graczyk in https://github.com/saleor/saleor-app-marketplace/issues/99#issuecomment-1288904097_

**Comment by lkostrowski** [comment]
Available on `canary` branch

**Comment by lkostrowski** [comment]
available also on main

**Comment by lkostrowski** [comment]
available also on main

**Comment by michalina-graczyk** [comment]
@lkostrowski PR is not linked to the issue, could you add it?

**Comment by lkostrowski** [comment]
It is linked, but it shouldn't be tested from branch. Its available on canary and main

![Zrzut ekranu 2022-10-28 o 11 12 33](https://user-images.githubusercontent.com/9268745/198550925-fd20990b-a77f-449b-b477-54c250b46684.png)
