### ISSUE TITLE
Form validation in app configuration

### ISSUE THREAD

**Issue by magul** [saleor/saleor-app-template#60]
Currently we have a React component and API route for building simple (textfields only) configuration page. Customer just need to define array of strings and our template would render form with these strings as names/labels of fields.

Currently, when user click a save button current values from the form are sent and saved in `privateMetadata`  of an app. It allows a situation, that you render that form for the first time, never put anything in textfields, click save and an app will save `privateMetadata`  with empty strings as values.

It would be great if we could pass validation callables, when creating that component/API route, to validate values in these fields (both in browser and on backend).

**Comment by lkostrowski** [comment]
@magul what is your proposal?

I assume this is related
https://github.com/saleor/saleor-app-template/blob/main/pages/api/configuration.ts#L26

So do we want to extend metadata field, to include validation config, so frontend (and backend) can use it?

It's not easy to do that declaratively. It will also introduce another library that we will show to the client.

Of course we can provide some simple MVP solution, that is basically a regex (or most likely an array of regexp + msg). What do you think?

**Comment by magul** [comment]
> So do we want to extend metadata field, to include validation config, so frontend (and backend) can use it?

I don't believe we want to extend metadata field in Saleor DB, ultimately the definition of what validation that field should pass is app specific and should be included in its source code.

Ultimately I believe it can be as simple as providing callable for every field that we want to store in configuration, so in https://github.com/saleor/saleor-app-template/blob/main/pages/api/configuration.ts#L18 instead of an array of strings we want to have an array (still array, just to be able to order them as we're pleased) of objects with `name` and `validator`, something like that:
```javascript
const CONFIGURATION_KEYS = [
  {
    name: "NUMBER_OF_ORDERS",
    validator: (value) => 
      if (!/^-?\d+$/.test(value)) {
        throw ValidationError("It's not an integer.");
      }
    },
  },
];
```

Of course separate discussion is how to validate that also in browser (so how to expose these callables also to React component in https://github.com/saleor/saleor-app-template/blob/main/pages/configuration.tsx but that's shouldn't be super tricky, as we use the same language here and there afterall.

**Comment by lkostrowski** [comment]
>I don't believe we want to extend metadata field in Saleor DB, ultimately the definition of what validation that field should pass is app specific and should be included in its source code.

Yea I mean the same

Regarding you example - this mus be serialized and saved to metadata right? So it can't be function. We can have something like this:

```
const CONFIGURATION_KEYS = [
  {
    name: "NUMBER_OF_ORDERS",
    validator: [
      {
        regexp: "/^-?\d+$/",
        errorMessage: "Its not an integer"
      },
      {
        regexp: "...",
        errorMessage: "Some other validator"
      }
    ]
  },
];
```

So I propose:
1. Serialized regexp so frontend and node contexts can use it (we can have shared util to parse it)
2. Array of validators - we might want several rules, so its better to compose validators than single, big one (also messages are limited)

**Comment by magul** [comment]
> Regarding you example - this mus be serialized and saved to metadata right? So it can't be function. We can have something like this:

the value has to be saved in metadata, there's no reason to store validator there thought (as it always is app-specific and can live in its code).

**Comment by lkostrowski** [comment]
Closing - we will remove example "demo" code from app template, making it very minimal, then - add new set of examples solving specific problems
