### ISSUE TITLE
Stop ignoring additional fields in manifest JSON (in Saleor core), just raise ValidationError

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-app-template#65]

**Comment by lkostrowski** [comment]
Calling @magul  - can you refine this topic?

**Comment by magul** [comment]
@lkostrowski so - this ticket should be created agains https://github.com/saleor/saleor, it was requested by @patrys and basically it's about (I don't really know if I'm not repeating myself)  raising a `ValidationError` in Saleor core, when fetched manifest from app contains unrecognized attribute.

Current (I guess), list of attributes is available here: https://docs.saleor.io/docs/3.x/developer/extending/apps/manifest, so currently if your manifest will contain
```
{
  ...
  someStrangeAttributeName: ...,
  ...
}
```
Saleor core will silently accept such thing, and the plan here is to deliver a functionality that will raise error in such situation.

(the other question is where to validate that? as we fetch manifest in two places currently, and I'm advocating for fetching that only once, and then relying on pre-fetched value, but we will discuss that in app upgrade flow discussion).

**Comment by lkostrowski** [comment]
@magul so should we close this on and add it to the Core?

@patrys can you explain why this should be so strict? I can refer to the https://en.wikipedia.org/wiki/Robustness_principle to just accept that, but I don't know the context

**Comment by patrys** [comment]
Being strict makes it easier to detect obvious problems like misspelled labels. It also means we can claim the entire namespace as our own without any possibility of conflict with fields that the community added for internal use.

**Comment by lkostrowski** [comment]
Will be covered in https://github.com/saleor/saleor-app-template/issues/140
