### ISSUE TITLE
Missed error message for a user in number of orders

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-app-template#81]
1. Create and deploy an app
2. Install app by saleor dashboard 
3. Wait untill you will see the configuration are (btw. here I had to wait very long to see it, maybe it's worth to add some loading?, for a user it may looks like nth is happening)
4. In numbers of orders type text or number 

Current result: I am getting an error - look at screenshot
Expected result: I am getting an notification that string or number is required.

![image](https://user-images.githubusercontent.com/25908728/189621960-24130b45-3afb-4234-93a9-7e4c74f0cd6f.png)

**Comment by lkostrowski** [comment]
Template changed, issue no longer valid.
